print("Hello World")
print("Nolan is still cool")
print("The comment before this is correct")
print("testing from Haley's laptop")
print("Chair Force")
print("Hello, this is Dr.Loria, congratiolations! You all recieve 100% on this assighnment.")